name: av2
phase: default

target:
  _target_: src.datamodule.av2_datamodule.Av2DataModule

  data_root: 'data/DeMo_processed'
  train_batch_size: ${batch_size}
  val_batch_size: ${batch_size}
  test_batch_size: ${batch_size}
  shuffle: True
  num_workers: ${num_workers}
  pin_memory: True
  dataset:
    num_historical_steps: 20
    num_future_steps: 80
    sequence_origins: [20]
    radius: 250.0
    train_mode: 'only_focal'